"""Artist agent — generates image prompts and calls image generation."""

from __future__ import annotations

import logging
import time
from pathlib import Path

import httpx

from storywizard.agents.base import BaseAgent
from storywizard.models import GeneratedPanel, Panel, PanelScript, VisualStyleGuide

logger = logging.getLogger(__name__)


class Artist(BaseAgent):
    """Creates image generation prompts and produces panel artwork.

    The Artist takes panel scripts and the visual style guide, then crafts
    detailed image generation prompts. Supports multiple backends:
    - "mock": saves prompts as text files (free, for testing)
    - "flux": uses Flux via fal.ai API (high quality, fast inference)
    """

    name = "Artist"
    system_prompt = (
        "You are a graphic novel artist who creates detailed image generation "
        "prompts. For each panel, you craft a prompt that:\n\n"
        "1. Describes the COMPOSITION — camera angle, framing, focal point\n"
        "2. Specifies CHARACTERS — their appearance, expression, pose, position\n"
        "3. Sets the ENVIRONMENT — background, lighting, atmosphere, weather\n"
        "4. Maintains STYLE CONSISTENCY — references the art style, color palette, "
        "and visual rules from the style guide\n"
        "5. Captures the EMOTION — the feeling the image should evoke\n\n"
        "Your prompts should be detailed enough for an AI image generator to "
        "produce a high-quality, consistent result. Always reference the style "
        "guide to maintain visual coherence across all panels.\n\n"
        "Keep prompts under 500 words. Be specific and visual, not abstract."
    )

    def generate_panels(
        self,
        scripts: list[PanelScript],
        style_guide: VisualStyleGuide,
        output_dir: Path,
    ) -> list[GeneratedPanel]:
        """Generate all panel images (or prompts in mock mode)."""
        output_dir.mkdir(parents=True, exist_ok=True)
        generated = []

        total = sum(len(s.panels) for s in scripts)
        count = 0

        for script in scripts:
            for panel in script.panels:
                count += 1
                logger.info(
                    "Generating panel %d/%d (scene %d, panel %d)",
                    count, total, script.scene_number, panel.panel_number,
                )
                prompt = self._craft_image_prompt(panel, script, style_guide)
                image_path = self._generate_image(
                    prompt, script.scene_number, panel.panel_number, output_dir
                )
                generated.append(
                    GeneratedPanel(
                        scene_number=script.scene_number,
                        panel_number=panel.panel_number,
                        image_prompt=prompt,
                        image_path=str(image_path),
                        alt_text=panel.visual_direction,
                    )
                )

        return generated

    def _craft_image_prompt(
        self, panel: Panel, script: PanelScript, style_guide: VisualStyleGuide
    ) -> str:
        """Use Claude to craft a detailed image generation prompt."""
        prompt = (
            f"Craft a detailed image generation prompt for this graphic novel panel.\n\n"
            f"SCENE: {script.scene_title}\n"
            f"PANEL {panel.panel_number} DIRECTION: {panel.visual_direction}\n"
            f"NARRATION: {panel.narration}\n\n"
            f"STYLE GUIDE:\n"
            f"- Art style: {style_guide.art_style}\n"
            f"- Color palette: {', '.join(style_guide.color_palette)}\n"
            f"- Mood: {style_guide.mood}\n"
            f"- Environment: {style_guide.environment_notes}\n"
            f"- Consistency rules: {'; '.join(style_guide.consistency_rules)}\n\n"
            f"Return ONLY the image generation prompt text, nothing else. "
            f"Keep it under 500 words."
        )
        return self.invoke(prompt)

    def _generate_image(
        self, prompt: str, scene_num: int, panel_num: int, output_dir: Path
    ) -> Path:
        """Generate an image using the configured backend."""
        filename = f"scene{scene_num:02d}_panel{panel_num:02d}"

        if self.config.image_backend == "mock":
            return self._mock_generate(prompt, filename, output_dir)
        elif self.config.image_backend == "flux":
            return self._flux_generate(prompt, filename, output_dir)
        else:
            raise NotImplementedError(
                f"Image backend '{self.config.image_backend}' not yet implemented. "
                f"Use 'mock' or 'flux'."
            )

    def _mock_generate(self, prompt: str, filename: str, output_dir: Path) -> Path:
        """Mock image generation — saves the prompt as a text file."""
        path = output_dir / f"{filename}.prompt.txt"
        path.write_text(
            f"[MOCK IMAGE — would be generated by AI image API]\n\n"
            f"IMAGE PROMPT:\n{prompt}\n",
            encoding="utf-8",
        )
        logger.info("Mock image saved: %s", path)
        return path

    def _flux_generate(self, prompt: str, filename: str, output_dir: Path) -> Path:
        """Generate an image using Flux via fal.ai API."""
        import fal_client

        model = self.config.flux_model
        logger.info("Calling Flux model via fal.ai: %s", model)

        result = fal_client.subscribe(
            model,
            arguments={
                "prompt": prompt,
                "image_size": self.config.flux_aspect_ratio,
                "num_images": 1,
                "output_format": "png",
            },
        )

        # fal.ai returns {"images": [{"url": "...", "width": ..., "height": ...}]}
        image_url = result["images"][0]["url"]

        # Download the image
        path = output_dir / f"{filename}.png"
        response = httpx.get(image_url, timeout=60.0)
        response.raise_for_status()
        path.write_bytes(response.content)

        # Also save the prompt alongside for reference
        prompt_path = output_dir / f"{filename}.prompt.txt"
        prompt_path.write_text(f"IMAGE PROMPT:\n{prompt}\n", encoding="utf-8")

        logger.info("Flux image saved: %s (%d bytes)", path, len(response.content))
        return path
